# Auto-generated from data/2026_MS_draw.md and data/2026_LS_draw.md
# (official Wimbledon 2026 singles draws). Order = draw position 1..128.
# Used to order the bracket view to match the real draw; ESPN's API does
# not expose draw positions. Each entry is [first_name, last_name].
MENS_DRAW_2026 = [
    ['Jannik', 'SINNER'],
    ['Miomir', 'KECMANOVIC'],
    ['Nuno', 'BORGES'],
    ['Tristan', 'BOYER'],
    ['Aleksandar', 'VUKIC'],
    ['Jenson', 'BROOKSBY'],
    ['Emilio', 'NAVA'],
    ['Ignacio', 'BUSE'],
    ['Rafael', 'JODAR'],
    ['Felix', 'GILL'],
    ['Denis', 'SHAPOVALOV'],
    ['Pablo', 'CARRENO BUSTA'],
    ['Shintaro', 'MOCHIZUKI'],
    ['Max', 'BASING'],
    ['Ethan', 'QUINN'],
    ['Luciano', 'DARDERI'],
    ['Casper', 'RUUD'],
    ['Hubert', 'HURKACZ'],
    ['Hamad', 'MEDJEDOVIC'],
    ['Sebastian', 'OFNER'],
    ['Soonwoo', 'KWON'],
    ['Martin', 'LANDALUCE'],
    ['Alexandre', 'MULLER'],
    ['Tommy', 'PAUL'],
    ['Brandon', 'NAKASHIMA'],
    ['Jack', 'PINNINGTON JONES'],
    ['Jan-Lennard', 'STRUFF'],
    ['Sebastian', 'BAEZ'],
    ['Camilo', 'UGO CARABELLI'],
    ['Daniel', 'MERIDA'],
    ['Marin', 'CILIC'],
    ['Daniil', 'MEDVEDEV'],
    ['Felix', 'AUGER-ALIASSIME'],
    ['Aleksandr', 'SHEVCHENKO'],
    ['Adam', 'WALTON'],
    ['Dino', 'PRIZMIC'],
    ['Adolfo Daniel', 'VALLEJO'],
    ['Nicolas', 'MEJIA'],
    ['Michael', 'ZHENG'],
    ['Cameron', 'NORRIE'],
    ['Alejandro', 'DAVIDOVICH FOKINA'],
    ['Juan Manuel', 'CERUNDOLO'],
    ['Thiago Agustin', 'TIRANTE'],
    ['Fabian', 'MAROZSAN'],
    ['Luca', 'VAN ASSCHE'],
    ['Marton', 'FUCSOVICS'],
    ['Dalibor', 'SVRCINA'],
    ['Learner', 'TIEN'],
    ['Andrey', 'RUBLEV'],
    ['Roman', 'SAFIULLIN'],
    ['Aleksandar', 'KOVACEVIC'],
    ['Botic', 'VAN DE ZANDSCHULP'],
    ['Jesper', 'DE JONG'],
    ['Rinky', 'HIJIKATA'],
    ['Roberto', 'BAUTISTA AGUT'],
    ['Joao', 'FONSECA'],
    ['Arthur', 'RINDERKNECH'],
    ['Oliver', 'TARVET'],
    ['Marco', 'TRUNGELLITI'],
    ['Martin', 'DAMM'],
    ['Hugo', 'GASTON'],
    ['Stefanos', 'TSITSIPAS'],
    ['Yibing', 'WU'],
    ['Novak', 'DJOKOVIC'],
    ['Alex', 'DE MINAUR'],
    ['Roman Andres', 'BURRUCHAGA'],
    ['Adrian', 'MANNARINO'],
    ['Titouan', 'DROGUET'],
    ['Pablo', 'LLAMAS RUIZ'],
    ['Zachary', 'SVAJDA'],
    ['Kamil', 'MAJCHRZAK'],
    ['Alejandro', 'TABILO'],
    ['Karen', 'KHACHANOV'],
    ['Billy', 'HARRIS'],
    ['Yannick', 'HANFMANN'],
    ['Giovanni', 'MPETSHI PERRICARD'],
    ['Tallon', 'GRIEKSPOOR'],
    ['James', 'DUCKWORTH'],
    ['Mariano', 'NAVONE'],
    ['Flavio', 'COBOLLI'],
    ['Jakub', 'MENSIK'],
    ['Toby', 'SAMUEL'],
    ['Dane', 'SWEENY'],
    ['Grigor', 'DIMITROV'],
    ['Stan', 'WAWRINKA'],
    ['Matteo', 'BERRETTINI'],
    ['Raphael', 'COLLIGNON'],
    ['Arthur', 'FILS'],
    ['Ugo', 'HUMBERT'],
    ['Zizou', 'BERGS'],
    ['Sho', 'SHIMABUKURO'],
    ['Jaime', 'FARIA'],
    ['Damir', 'DZUMHUR'],
    ['Arthur', 'FERY'],
    ['Otto', 'VIRTANEN'],
    ['Ben', 'SHELTON'],
    ['Taylor', 'FRITZ'],
    ['Dusan', 'LAJOVIC'],
    ['Patrick', 'KYPSON'],
    ['Mackenzie', 'MCDONALD'],
    ['Benjamin', 'BONZI'],
    ['Gabriel', 'DIALLO'],
    ['Lorenzo', 'SONEGO'],
    ['Tomas Martin', 'ETCHEVERRY'],
    ['Frances', 'TIAFOE'],
    ['Terence', 'ATMANE'],
    ['Vit', 'KOPRIVA'],
    ['Jan', 'CHOINSKI'],
    ['Kyrian', 'JACQUET'],
    ['Vilius', 'GAUBAS'],
    ['Thanasi', 'KOKKINAKIS'],
    ['Alexander', 'BUBLIK'],
    ['Jiri', 'LEHECKA'],
    ['Alexei', 'POPYRIN'],
    ['Alex', 'MOLCAN'],
    ['Daniel', 'ALTMAIER'],
    ['Alex', 'MICHELSEN'],
    ['Jacob', 'FEARNLEY'],
    ['Jaume', 'MUNAR'],
    ['Francisco', 'CERUNDOLO'],
    ['Matteo', 'ARNALDI'],
    ['Quentin', 'HALYS'],
    ['Corentin', 'MOUTET'],
    ['Marcos', 'GIRON'],
    ['Valentin', 'ROYER'],
    ['Harry', 'WENDELKEN'],
    ['Alexander', 'BLOCKX'],
    ['Alexander', 'ZVEREV'],
]

WOMENS_DRAW_2026 = [
    ['Aryna', 'SABALENKA'],
    ['Teodora', 'KOSTOVIC'],
    ['Oleksandra', 'OLIYNYKOVA'],
    ['McCartney', 'KESSLER'],
    ['Jelena', 'OSTAPENKO'],
    ['Harriet', 'DART'],
    ['Antonia', 'RUZIC'],
    ['Darja', 'SEMENISTAJA'],
    ['Leylah', 'FERNANDEZ'],
    ['Janice', 'TJEN'],
    ['Mimi', 'XU'],
    ['Daria', 'KASATKINA'],
    ['Anastasia', 'GASANOVA'],
    ['Emiliana', 'ARANGO'],
    ['Elsa', 'JACQUEMOT'],
    ['Naomi', 'OSAKA'],
    ['Karolina', 'MUCHOVA'],
    ['Anastasia', 'ZAKHAROVA'],
    ['Bianca', 'ANDREESCU'],
    ['Shuai', 'ZHANG'],
    ['Alycia', 'PARKS'],
    ['Alicia', 'DUDENEY'],
    ['Mananchaya', 'SAWANGKAEW'],
    ['Maja', 'CHWALINSKA'],
    ['Katerina', 'SINIAKOVA'],
    ['Qinwen', 'ZHENG'],
    ['Peyton', 'STEARNS'],
    ['Nikola', 'BARTUNKOVA'],
    ['Barbora', 'KREJCIKOVA'],
    ['Hannah', 'KLUGMAN'],
    ['Magda', 'LINETTE'],
    ['Mirra', 'ANDREEVA'],
    ['Jessica', 'PEGULA'],
    ['Darja', 'VIDMANOVA'],
    ['Sara', 'SORRIBES TORMO'],
    ['Victoria', 'JIMENEZ KASINTSEVA'],
    ['Dayana', 'YASTREMSKA'],
    ['Aoi', 'ITO'],
    ['Jessica', 'BOUZAS MANEIRO'],
    ['Anastasia', 'POTAPOVA'],
    ['Ekaterina', 'ALEXANDROVA'],
    ['Panna', 'UDVARDY'],
    ['Lanlana', 'TARARUDEE'],
    ['Lilli', 'TAGGER'],
    ['Yulia', 'PUTINTSEVA'],
    ['Tatjana', 'MARIA'],
    ['Jaqueline', 'CRISTIAN'],
    ['Iva', 'JOVIC'],
    ['Belinda', 'BENCIC'],
    ['Mika', 'STOJSAVLJEVIC'],
    ['Xinyu', 'WANG'],
    ['Elisabetta', 'COCCIARETTO'],
    ['Francesca', 'JONES'],
    ['Diane', 'PARRY'],
    ['Magdalena', 'FRECH'],
    ['Anna', 'KALINSKAYA'],
    ['Ann', 'LI'],
    ['Zeynep', 'SONMEZ'],
    ['Claire', 'LIU'],
    ['Hanne', 'VANDEWINKEL'],
    ['Solana', 'SIERRA'],
    ['Anna', 'BONDAR'],
    ['Tamara', 'KORPATSCH'],
    ['Coco', 'GAUFF'],
    ['Elina', 'SVITOLINA'],
    ['Daria', 'SNIGUR'],
    ['Veronika', 'ERJAVEC'],
    ['Leolia', 'JEANJEAN'],
    ['Ajla', 'TOMLJANOVIC'],
    ['Mariam', 'BOLKVADZE'],
    ['Ashlyn', 'KRUEGER'],
    ['Donna', 'VEKIC'],
    ['Emma', 'NAVARRO'],
    ['Paula', 'BADOSA'],
    ['Oksana', 'SELEKHMETEVA'],
    ['Sinja', 'KRAUS'],
    ['Yuliia', 'STARODUBTSEVA'],
    ['Anna', 'BLINKOVA'],
    ['Nadia', 'PODOROSKA'],
    ['Marta', 'KOSTYUK'],
    ['Jasmine', 'PAOLINI'],
    ['Robin', 'MONTGOMERY'],
    ['Iryna', 'SHYMANOVICH'],
    ['Viktorija', 'GOLUBIC'],
    ['Anhelina', 'KALININA'],
    ['Kamilla', 'RAKHIMOVA'],
    ['Maria', 'SAKKARI'],
    ['Clara', 'TAUSON'],
    ['Alexandra', 'EALA'],
    ['Renata', 'ZARAZUA'],
    ['Serena', 'WILLIAMS'],
    ['Maya', 'JOINT'],
    ['Tereza', 'VALENTOVA'],
    ['Karolina', 'PLISKOVA'],
    ['Taylor', 'TOWNSEND'],
    ['Iga', 'SWIATEK'],
    ['Amanda', 'ANISIMOVA'],
    ['Lina', 'GJORCHESKA'],
    ['Petra', 'MARCINKO'],
    ['Sofia', 'KENIN'],
    ['Irina-Camelia', 'BEGU'],
    ['Katie', 'SWAN'],
    ['Kayla', 'DAY'],
    ['Madison', 'KEYS'],
    ['Sorana', 'CIRSTEA'],
    ['Sara', 'BEJLEK'],
    ['Kimberly', 'BIRRELL'],
    ['Alina', 'KORNEEVA'],
    ['Camila', 'OSORIO'],
    ['Simona', 'WALTERT'],
    ['Ella', 'SEIDEL'],
    ['Linda', 'NOSKOVA'],
    ['Diana', 'SHNAIDER'],
    ['Eva', 'LYS'],
    ['Polina', 'KUDERMETOVA'],
    ['Liudmila', 'SAMSONOVA'],
    ['Katie', 'BOULTER'],
    ['Tyra Caterina', 'GRANT'],
    ['Talia', 'GIBSON'],
    ['Marie', 'BOUZKOVA'],
    ['Elise', 'MERTENS'],
    ['Laura', 'SIEGEMUND'],
    ['Beatriz', 'HADDAD MAIA'],
    ['Maria', 'TIMOFEEVA'],
    ['Elena-Gabriela', 'RUSE'],
    ['Caty', 'MCNALLY'],
    ['Lois', 'BOISSON'],
    ['Elena', 'RYBAKINA'],
]
